### PR TITLE
Fix #21: Confetti Overlay over Successful Product Name

### LINKED ISSUE #21: [BUG] Unable to click on product names after successful guess in Bildval
**Describe the bug**

After a successful guess in Bildval, the item name is not clickable. This works for all the other options, or all if you fail a guess.

**To Reproduce**

1. Navigate to Bildval, start a round
2. Make a successful guess
3. The product name is not clickable

**Expected behavior**

Product name should be clickable.

**Screenshots**

https://github.com/avikantz/ikea-word-games/assets/7699509/ff21f2aa-cac5-479b-b938-51a125dfe5e5

**Additional context**

Suspect it has something to do with the confetti.

### PR DESCRIPTION
**Pull request by AnuMessi10**
**Fixes**: #21 

**Description**: On making a successful guess in the Bildval game, the confetti overlay makes the product-name un-clickable.

**Solution**: This was being caused due to setting the state of the confetti to true inside the onClick handler, once the confetti is shown and the success audio is played I have added a short delay of 500 ms thereby hiding the overlay.

**Tags**: `bug`, `hacktoberfest`

### CODE REVIEW

File: src/components/bildval/guessOption.tsx [hunk 1]
```diff
@@ -39,9 +39,11 @@ export const BildvalGuessOption = ({
       // Check if correct
       if (solution?.id === guess.id) {
         // Show confetti
-        setSuccess(true);
+        setShowConfetti(true);
         // Play success audio
         playSuccessAudio?.();
+        // Hide Confetti with a delay of 500 ms
+        setTimeout(() => setShowConfetti(false), 500);
```
Comment (avikantz) [inline src/components/bildval/guessOption.tsx:46]: The delay timing is a bit short, the confetti ends abruptly.

Suggest increasing to 1.5-2s till the confetti has subsided, thanks

Comment (AnuMessi10) [reply src/components/bildval/guessOption.tsx]: Sure, I have increased the delay to 1.5s.

**Review by avikantz — APPROVED** [review]
Works, thanks @AnuMessi10
